# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
install:
- R -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
- R -e 'devtools::install_deps(dep = T)'
script:
- travis_wait R CMD build .
- travis_wait R CMD check *tar.gz
after_success:
- R -e 'library(covr); codecov()'
