// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MarkovTraceAndValues
List MarkovTraceAndValues(NumericMatrix transitions, List values, NumericVector init, int ncycles, int nstates, int nvalues, double ccons);
RcppExport SEXP _heRomod2_MarkovTraceAndValues(SEXP transitionsSEXP, SEXP valuesSEXP, SEXP initSEXP, SEXP ncyclesSEXP, SEXP nstatesSEXP, SEXP nvaluesSEXP, SEXP cconsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< List >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type ncycles(ncyclesSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< int >::type nvalues(nvaluesSEXP);
    Rcpp::traits::input_parameter< double >::type ccons(cconsSEXP);
    rcpp_result_gen = Rcpp::wrap(MarkovTraceAndValues(transitions, values, init, ncycles, nstates, nvalues, ccons));
    return rcpp_result_gen;
END_RCPP
}
// cppMarkovTransitionsAndTrace
List cppMarkovTransitionsAndTrace(NumericMatrix transitions, NumericVector initialProbs, CharacterVector stateNames, int nCycles, int nStates, double complementConstant);
RcppExport SEXP _heRomod2_cppMarkovTransitionsAndTrace(SEXP transitionsSEXP, SEXP initialProbsSEXP, SEXP stateNamesSEXP, SEXP nCyclesSEXP, SEXP nStatesSEXP, SEXP complementConstantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialProbs(initialProbsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type stateNames(stateNamesSEXP);
    Rcpp::traits::input_parameter< int >::type nCycles(nCyclesSEXP);
    Rcpp::traits::input_parameter< int >::type nStates(nStatesSEXP);
    Rcpp::traits::input_parameter< double >::type complementConstant(complementConstantSEXP);
    rcpp_result_gen = Rcpp::wrap(cppMarkovTransitionsAndTrace(transitions, initialProbs, stateNames, nCycles, nStates, complementConstant));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heRomod2_MarkovTraceAndValues", (DL_FUNC) &_heRomod2_MarkovTraceAndValues, 7},
    {"_heRomod2_cppMarkovTransitionsAndTrace", (DL_FUNC) &_heRomod2_cppMarkovTransitionsAndTrace, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_heRomod2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
