# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fill3dArray <- function(x, y, z, value, dims) {
    .Call(`_heRomod2_fill3dArray`, x, y, z, value, dims)
}

rcpp_hello_world <- function() {
    .Call(`_heRomod2_rcpp_hello_world`)
}

